name: flutter_story
description: A Flutter story application with authentication and story management.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  device_info_plus: ^11.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  go_router: ^15.1.2
  google_fonts: ^6.1.0
  http: ^1.1.2
  image_picker: ^1.0.4
  intl: ^0.20.2
  path: ^1.8.3
  permission_handler: ^12.0.0+1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  # assets:
  #   - assets/images/
  #   - assets/icons/
